- docs/developer-guide/kvscheduler.md
- docs/developer-guide/model-registration.md
- docs/developer-guide/plugin-lookup.md
- docs/plugins/connection-plugins.md
- mkdocs.yml
> add model registration article

- docs/user-guide/concepts.md
- docs/user-guide/config-files.md
- mkdocs.yml
> updated config files

- docs/developer-guide/control-flows.md
- docs/developer-guide/kvdescriptor.md
- docs/developer-guide/kvscheduler.md
- docs/developer-guide/model-registration.md
- docs/developer-guide/plugin-lookup.md
- docs/plugins/core-vpp-plugins.md
- docs/plugins/db-plugins.md
- docs/plugins/infra-plugins.md
- docs/plugins/linux-plugins.md
- docs/plugins/other-vpp-plugins.md
- docs/plugins/plugin-overview.md
- docs/tutorials/04_kv-store.md
- docs/tutorials/05_kv-scheduler.md
- docs/user-guide/arm64.md
- docs/user-guide/concepts.md
- docs/user-guide/config-files.md
- docs/user-guide/get-agent.md
- docs/user-guide/quickstart.md
- mkdocs.yml
> docs improvements

- docs/tutorials/01_hello-world.md
- docs/tutorials/02_plugin-deps.md
- docs/tutorials/03_rest-handler.md
- docs/tutorials/04_kv-store.md
- docs/tutorials/05_kv-scheduler.md
- docs/tutorials/06_plugin-lookup.md
- docs/tutorials/07_vpp-connection.md
- docs/tutorials/08_grpc-tutorial.md
> tutorials clean up, added links to code

- docs/user-guide/quickstart.md
Signed-off-by: yf-yang <directoryyf@gmail.com>
> fix corrupt command

- docs/intro/framework.md
- mkdocs.yml
Signed-off-by: Ondrej Fabry <ofabry@cisco.com>
> Rename Agent to Framework in Intro section (fixes #15)

- docs/user-guide/examples.md
- docs/user-guide/get-agent.md
- mkdocs.yml
> examples and agent executables

- docs/user-guide/reference.md
> updated key reference

- docs/plugins/infra-plugins.md
- docs/user-guide/vpp-cli.md
> readme for supervisor plugin

- docs/plugins/infra-plugins.md
> Update supervisor plugin readme

- docs/developer-guide/control-flows.md
- docs/developer-guide/kvscheduler.md
commit 1 is dev guide/control flows/af-packet interface fixes
> developer guide fix ups #2

- docs/developer-guide/kvdescriptor.md
- docs/developer-guide/kvs-troubleshooting.md
- docs/developer-guide/kvscheduler.md
first commit - Value entered via NB was not configured in SB
> dev guide kvs troubleshoot fix ups

- docs/intro/faq.md
- docs/intro/framework.md
- docs/intro/overview.md
- docs/plugins/linux-plugins.md
- docs/plugins/vpp-plugins.md
- docs/user-guide/agentctl.md
- docs/user-guide/arm64.md
- docs/user-guide/concepts.md
- docs/user-guide/config-files.md
- docs/user-guide/examples.md
- docs/user-guide/get-vpp-agent.md
- docs/user-guide/quickstart.md
- mkdocs.yml
- agentctl updated text, examples, pointers, fixups
- vpp plugins updated text, pointers, fix ups
- misc quickstart, vpp agent setup
> Docupdates8

- docs/api/api-kvs.md
- docs/api/api-vpp-agent.md
- docs/developer-guide/build-vpp-agent-no-image.md
- docs/developer-guide/kvscheduler.md
- docs/developer-guide/ligatoAPI.md
- docs/developer-guide/model-registration.md
- docs/developer-guide/plugin-lookup.md
- docs/index.md
- docs/intro/faq.md
- docs/plugins/connection-plugins.md
- docs/plugins/kvs-plugin.md
- docs/plugins/linux-plugins.md
- docs/plugins/vpp-plugins.md
- docs/troubleshooting/config-ts.md
- docs/troubleshooting/startup-ts.md
- docs/tutorials/05_kv-scheduler.md
- docs/tutorials/08_grpc-tutorial.md
- docs/user-guide/arm64.md
- docs/user-guide/quickstart.md
- docs/user-guide/reference.md
- docs/user-guide/vpp-cli.md
- mkdocs.yml
Updates:
- created new API section for vpp agent and kvs rest api; included URL and sample responses
- synced/xref API section with other sections containing rest
- reformatted/updated vpp cli
- reformatted/updated key reference to include all known keys 
- replaced vpp-agent with VPP agent in docs text
- various other cleanups
> Docupdates12

- docs/api/api-vpp-agent.md
- docs/plugins/vpp-plugins.md
- docs/user-guide/agentctl.md
included telemetry plugin pointers to telemetry APIs, minimal cosmetic fixes
> updated VPP agent API and Agentctl with REST version info

- docs/testing/end-to-end-tests.md
- docs/testing/integration-tests.md
- docs/user-guide/agentctl.md
- docs/user-guide/quickstart.md
- mkdocs.yml
Added section on e2e testing. Updated agentctl section covering new config commands and dump json formatting.
https://github.com/ligato/docs/issues/70
https://github.com/ligato/docs/issues/69
> metz-e2e-test-agentctl-updates

- docs/tutorials/00_tutorial-setup.md
- docs/tutorials/01_hello-world.md
- docs/tutorials/02_plugin-deps.md
- docs/tutorials/03_rest-handler.md
- docs/tutorials/04_kv-store.md
- docs/tutorials/05_kv-scheduler.md
- docs/tutorials/06_plugin-lookup.md
- docs/tutorials/07_vpp-connection.md
- docs/tutorials/08_grpc-tutorial.md
- edits for conforming to developer style guide recommendations.
> Tutorial updates

- docs/developer-guide/kvs-troubleshooting.md
- docs/plugins/db-plugins.md
- docs/plugins/infra-plugins.md
- docs/plugins/vpp-plugins.md
- docs/user-guide/reference.md
db plugins updates
infra plugins updates
vpp plugins scrub
> DB and infra plugins updates

- docs/user-guide/concepts.md
- added resync and plugins sections
- updated VPP Configuration Order
- style and readability updates to using VPP CLI using KV Scheduler
- Various style and readability edits
> Concepts section update

- docs/user-guide/concepts.md
- edited/cleaned-up/clarified keys and microservice label section in concepts.md
- updated kvdb-microservice-label diagram.
- various readability improvements.
> metz microservicelabel section cleanup

- docs/user-guide/get-vpp-agent.md
- docs/user-guide/quickstart.md
- minor reorganization of section topics
- enhanced text clarity, added pointers, fixed typos
> user guide vpp agent updates

- docs/plugins/custom-plugin.md
- mkdocs.yml
- based on https://github.com/ligato/vpp-agent/discussions/1624
> Added new custom plugin section

- docs/user-guide/examples.md
- docs/user-guide/get-vpp-agent.md
- mkdocs.yml
- moved arm64 content to vpp agent setup and called arm64 considerations
- fixed typos and punctuation bugs in get-vpp-agent.md
> arm64 content updates and move

- docs/api/api-vpp-agent.md
based on https://github.com/ligato/vpp-agent/pull/1784
> added config json schema rest api

- docs/api/api-vpp-agent.md
Updated and reformatted VPP agent REST API section (api-vpp-agent.md) based on:
https://github.com/ligato/vpp-agent/pull/1786
https://github.com/ligato/vpp-agent/pull/1787
Included examples.
> Update VPP agent API docs section for #1786 and #1787

- docs/user-guide/get-vpp-agent.md
per https://github.com/ligato/vpp-agent/issues/1797 and https://github.com/ligato/docs/issues/103
> fixed and tested docker run command typos

- docs/intro/overview.md
punctuation and typos clean up in overview.md page.
> Fix overview.md page typos
